[profile.default]
src = "src"
out = "out"
libs = ["lib"]
sender = "0x04f48FDf309c6FF815Bf0eF5a855327B41dC9809"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/082cfa040f504515b692e80fe75424ce"
